name: 'Islandora Vocabularies'
description: 'Starter taxonomy vocabularies for use with Islandora.'
type: 'islandora'
install:
  - controlled_access_terms_defaults
config:
  install:
    controlled_access_terms_defaults:
      - field.field.taxonomy_term.corporate_body.field_authority_link.yml
      - field.field.taxonomy_term.corporate_body.field_cat_date_begin.yml
      - field.field.taxonomy_term.corporate_body.field_cat_date_end.yml
      - field.field.taxonomy_term.corporate_body.field_corp_alt_name.yml
      - field.field.taxonomy_term.corporate_body.field_relationships.yml
      - field.field.taxonomy_term.corporate_body.field_type.yml
      - field.field.taxonomy_term.family.field_authority_link.yml
      - field.field.taxonomy_term.family.field_cat_date_begin.yml
      - field.field.taxonomy_term.family.field_cat_date_end.yml
      - field.field.taxonomy_term.family.field_relationships.yml
      - field.field.taxonomy_term.genre.field_authority_link.yml
      - field.field.taxonomy_term.geo_location.field_authority_link.yml
      - field.field.taxonomy_term.geo_location.field_geo_alt_name.yml
      - field.field.taxonomy_term.geo_location.field_geo_broader.yml
      - field.field.taxonomy_term.geo_location.field_geo_geolocation.yml
      - field.field.taxonomy_term.language.field_authority_link.yml
      - field.field.taxonomy_term.person.field_alternate_name.yml
      - field.field.taxonomy_term.person.field_authority_link.yml
      - field.field.taxonomy_term.person.field_cat_date_begin.yml
      - field.field.taxonomy_term.person.field_cat_date_end.yml
      - field.field.taxonomy_term.person.field_relationships.yml
      - field.field.taxonomy_term.physical_form.field_authority_link.yml
      - field.field.taxonomy_term.resource_types.field_authority_link.yml
      - field.field.taxonomy_term.subject.field_authority_link.yml
      - field.field.taxonomy_term.temporal_subjects.field_authority_link.yml
      - field.storage.taxonomy_term.field_alternate_name.yml
      - field.storage.taxonomy_term.field_authority_link.yml
      - field.storage.taxonomy_term.field_cat_date_begin.yml
      - field.storage.taxonomy_term.field_cat_date_end.yml
      - field.storage.taxonomy_term.field_corp_alt_name.yml
      - field.storage.taxonomy_term.field_geo_alt_name.yml
      - field.storage.taxonomy_term.field_geo_broader.yml
      - field.storage.taxonomy_term.field_geo_geolocation.yml
      - field.storage.taxonomy_term.field_relationships.yml
      - field.storage.taxonomy_term.field_type.yml
      - language.content_settings.taxonomy_term.corporate_body.yml
      - language.content_settings.taxonomy_term.family.yml
      - language.content_settings.taxonomy_term.genre.yml
      - language.content_settings.taxonomy_term.geo_location.yml
      - language.content_settings.taxonomy_term.language.yml
      - language.content_settings.taxonomy_term.person.yml
      - language.content_settings.taxonomy_term.physical_form.yml
      - language.content_settings.taxonomy_term.resource_types.yml
      - language.content_settings.taxonomy_term.subject.yml
      - language.content_settings.taxonomy_term.temporal_subjects.yml
      - taxonomy.vocabulary.corporate_body.yml
      - taxonomy.vocabulary.family.yml
      - taxonomy.vocabulary.genre.yml
      - taxonomy.vocabulary.geo_location.yml
      - taxonomy.vocabulary.language.yml
      - taxonomy.vocabulary.person.yml
      - taxonomy.vocabulary.physical_form.yml
      - taxonomy.vocabulary.resource_types.yml
      - taxonomy.vocabulary.subject.yml
      - taxonomy.vocabulary.temporal_subjects.yml
